# Generated by Django 4.1.3 on 2023-09-01 16:45

import Prjt_exhb.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('smester', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('student1', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no1', models.CharField(blank=True, max_length=50, null=True)),
                ('img1', models.ImageField(upload_to=Prjt_exhb.models.get_group_upload_path)),
                ('student2', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no2', models.CharField(blank=True, max_length=50, null=True)),
                ('img2', models.ImageField(upload_to=Prjt_exhb.models.get_group_upload_path)),
                ('student3', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_no3', models.CharField(blank=True, max_length=50, null=True)),
                ('img3', models.ImageField(upload_to=Prjt_exhb.models.get_group_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('thumbnail', models.ImageField(upload_to=Prjt_exhb.models.get_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prjt_exhb.categories')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prjt_exhb.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('qualif', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('qualif', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.FloatField(blank=True, null=True)),
                ('score2', models.FloatField(blank=True, null=True)),
                ('score3', models.FloatField(blank=True, null=True)),
                ('score4', models.FloatField(blank=True, null=True)),
                ('score5', models.FloatField(blank=True, null=True)),
                ('reviewText', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prjt_exhb.project')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prjt_exhb.reviewer')),
            ],
        ),
    ]
