# Generated by Django 4.1.3 on 2023-09-01 17:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prjt_exhb', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True),
        ),
    ]
