# Generated by Django 4.1.3 on 2023-09-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prjt_exhb', '0006_alter_group_user_alter_project_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_supervisor', to='Prjt_exhb.supervisor'),
        ),
    ]
