# Generated by Django 4.1.3 on 2023-09-03 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prjt_exhb', '0007_alter_project_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='img1',
            new_name='lead_member_img',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='roll_no1',
            new_name='lead_member_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='student1',
            new_name='lead_member_phone',
        ),
        migrations.AddField(
            model_name='group',
            name='lead_roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
